server:
  port: 8081

spring:
  profiles:
    active: dev

---

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:10.0.16.36}:5432/${DB_NAME:infra_db_dev}?currentSchema=${DB_SCHEMA:public}
    username: ${DB_USERNAME:pushpendra}
    password: ${DB_PASSWORD:pushpendra_infradbdev#2025}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

auth:
  service:
    base-url: ${AUTH_SERVICE_BASE_URL:http://localhost:8080/api/auth/validate}

jwt:
  secret: ${JWT_SECRET:ThisIsA64CharacterSecretKeyForHS512Algorithm1234567890AbCdEfGhIjKlMnOpQrStUvWxYz!!}
  expiration-ms: 10800000

